# Generated by Django 3.2 on 2022-10-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
