# Generated by Django 3.2 on 2022-12-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=10000, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('commencement_date', models.DateField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
