# Generated by Django 3.2 on 2021-10-29 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000, null=True)),
                ('middle_name', models.CharField(max_length=1000, null=True)),
                ('last_name', models.CharField(max_length=1000, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('image_64', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=1000, null=True)),
                ('additional_data', models.JSONField(default=dict, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
