# Generated by Django 3.2 on 2021-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='additional_data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
