# Generated by Django 3.2 on 2021-12-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=11, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=11, null=True)),
                ('dob', models.DateField(null=True)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ufather', to='TreeBio.treebio')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umother', to='TreeBio.treebio')),
                ('spouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uspouse', to='TreeBio.treebio')),
            ],
        ),
    ]
