# Generated by Django 3.2 on 2021-12-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeBio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treebio',
            name='father',
        ),
        migrations.RemoveField(
            model_name='treebio',
            name='mother',
        ),
        migrations.AddField(
            model_name='treebio',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='TreeBio.treebio'),
        ),
        migrations.CreateModel(
            name='TreeBio2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=11, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=11, null=True)),
                ('dob', models.DateField(null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='TreeBio.treebio2')),
                ('spouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uspouse', to='TreeBio.treebio2')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
