# Generated by Django 3.2 on 2021-12-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeBio', '0002_auto_20211207_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='treebio2',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treebio2',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
