# Generated by Django 3.2 on 2022-10-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeBio', '0004_auto_20221005_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='treebio2',
            name='surname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
