# Generated by Django 3.2 on 2022-10-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeBio', '0005_treebio2_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treebio2',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'Female')], max_length=11, null=True),
        ),
    ]
