# Generated by Django 3.2 on 2022-12-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeBio', '0007_treebio2_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treebio2',
            old_name='avatar',
            new_name='family_image',
        ),
    ]
